### ISSUE TITLE
Include main website in read me 

### ISSUE THREAD

**Issue by tomgiagtz** [BoostIO/BoostHub#3]
Just thought the read me could use the link to the boosthub site

Great job with the custom blocks, really excited to try it out

P.S. - here’s the link so you can just copy paste it:

https://boosthub.io/

**Comment by Rokt33r** [comment]
Thanks for mentioning

**Comment by kazup01** [comment]
Hey @tomgiagtz , thanks for your suggestion!

Do you have any ideas for improving your team's efficiency with the custom block?
We'd be happy to support you for example, integrate Boost Hub with other services, create a custom block for you and so on, so let me know!
